---
title: "Basic usage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Basic usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all("~/Git/uk-covid-datatools/")
#devtools::install_github("terminological/uk-covid-datatools", force = TRUE)

dpc = tsp = NULL

reload = function() {
  devtools::load_all("~/Git/uk-covid-datatools/")
  dpc <<- DataProviderController$setup("~/Data/maps/", "~/S3/encrypted")
  tsp <<- dpc$timeseriesProcessor()
  # tsp$printSerialInterval()
  # chp <<- dpc$chessProcessor()
  # srv <<- dpc$survivalProcessor()
  # mwp <<- dpc$metawardProcessor()
}

reload()



```

# Get data and cleanse:

```{r}

testData = dpc$datasets$getPHEApi()

```

timeseries has UK region, England NHS region, and England Unitary Authority

# Calculate groupwise Rt (data is already grouped on uk_region)

```{r}


testData %>% tsp$plotIncidenceQuantiles(colour = statistic)


```
```{r}

reload()
tn = SerialIntervalProvider$truncatedNormals(dpc)
tsp$serial = tn


```

```{r}
tmp = testData %>% tsp$estimateRtWithAssumptions(period = 60,quick=TRUE,nocache=TRUE)
tmp %>% tsp$adjustRtDates() %>% tsp$adjustRtCorrFac() %>% tsp$plotRt(colour=statistic, rtlim = c(0,10), dates = "2020-02-01")
```