---
title: "Cori method"
author: "Rob Challen"
date: "04/09/2020"
output: 
  pdf_document :
    fig_caption: yes
header-includes:
 \usepackage{float}
 \floatplacement{figure}{H}    

knit: (function(inputFile, encoding,...) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "~/Dropbox/covid19/serial-interval/", output_file=paste0('cori-method-',Sys.Date(),'.pdf')) })
fig_width: 7
fig_height: 5
out.width: "100%"
bibliography: serial-interval.bib
csl: current-rt.csl
vignette: >
  %\VignetteIndexEntry{COVID-19 Serial Intervals}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = TRUE
)
```

## Cori method

Assume $I_t$ is a Poisson distribution:


$$
\begin{aligned}
E[I_t] &= R_t \sum_{s=1}^t I_{t-s}\omega_s \\
\Lambda_t &= \sum_{s=1}^t I_{t-s}\omega_s \\
P(I_t | I_0,\dots,I_{t-1},\omega,R_t) &= \frac{(R_t\Lambda_t)^{I_t}e^{-R_t\Lambda_t}}{I_t!}
\end{aligned}
$$

Assuming $R$ is constant over $[t-\tau+1;t]$ (and defined as $R_{t,\tau}$). If $R_{t,\tau}$ is assumed to be gamma distributed with shape parameter $a$ and scale parameter $b$ then by definition:


$$
\begin{aligned}
P(R_{t,\tau}) = \frac{R_{t,\tau}^{a-1}e^{\frac{-R_{t,\tau}}{b}}}{\Gamma(a)b^a}
\end{aligned}
$$

The likelihood of incidence observed within the time period $[t-\tau+1;t]$, given what we know about preceding time periods is:


$$
\begin{aligned}
P(I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-1},\omega,R_{t,\tau}) &= \prod_{s=t-\tau+1}^t\frac{(R_{t,\tau}\Lambda_s)^{I_s}e^{-R_{t,\tau}\Lambda_s}}{I_s!}
\\
&=
R_{t,\tau}^{\sum_{s=t-\tau+1}^t I_s}
e^{
  -R_{t,\tau}
  \big(
    \sum_{s=t-\tau+1}^t \Lambda_s
  \big)
}
\prod_{s=t-\tau+1}^t\frac{\Lambda_s^{I_s}}{I_s!}
\end{aligned}
$$

Applying Bayes rule the posterior joint distribution of $I_{t-\tau+1}, \dots,I_t, R_{t,\tau}$ conditioned on $I_0,\dots,I_{t-1},\omega$ :


$$
\begin{aligned}
P(I_{t-\tau+1}, \dots,I_t, R_{t,\tau} | I_0,\dots,I_{t-1},\omega) &=
P(I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-\tau},\omega,R_{t,\tau})
P_{prior}(R_{t,\tau}) \\
&=
\Bigg(
  \prod_{s=t-\tau+1}^t\frac{(R_{t,\tau}\Lambda_t)^{I_s}e^{-R_{t,\tau}\Lambda_s}}{I_s!}
\Bigg)
\Bigg(
  \frac{R_{t,\tau}^{a-1}e^{\frac{-R_{t,\tau}}{b}}}{\Gamma(a)b^a}
\Bigg)
\\
&=
R_{t,\tau}^{a-1+\sum_{s=t-\tau+1}^t I_s}e^{-R_{t,\tau}\big(\frac{1}{b}+\sum_{s=t-\tau+1}^t \Lambda_s\big)}
\Bigg(
  \prod_{s=t-\tau+1}^t\frac{\Lambda_s^{I_s}}{I_s!}
\Bigg)
\Bigg(
  \frac{1}{
    \Gamma(a)b^a
  }
\Bigg)
\end{aligned}
$$

Noting that the form is similar a gamma with shape $\kappa$ and scale $\theta$:


$$
\begin{aligned}
\kappa &= a+\sum_{s=t-\tau+1}^t I_s \\
\theta &= \frac{1}{b}+\sum_{s=t-\tau+1}^t \Lambda_s \\
\operatorname{P_{post}}(R_{t,\tau}) &=
R_{t,\tau}^{\kappa-1}e^{\frac{-R_{t,\tau}}{\theta}}
\Big(
  \frac{
    1
  }{
    \Gamma(\kappa)\theta^\kappa
  }
\Big) \\
\frac{
  \operatorname{P}(I_{t-\tau+1}, \dots,I_t, R_{t,\tau} | I_0,\dots,I_{t-1},\omega)
}{
  \operatorname{P_{post}}(R_{t,\tau})
} &=
  \prod_{s=t-\tau+1}^t\frac{\Lambda_s^{I_s}}{I_s!}
\frac{
  \Gamma(\kappa)\theta^\kappa
}{
  \Gamma(a)b^a
}
\end{aligned}
$$

## If cases not observed

as before define $\omega_s$ as infectivity profile (given an infection occurred, likelihood of the infection occurred s days ago), and an observation profile, $\lambda_u$ - the probability of an observation relating to an infection that occurred u days ago, given the observation is made, and $\psi$ the probability that an observation is made at all:


$$
\begin{aligned}
\omega_t &= \operatorname{P}(I_{X \to Y,t}|I_{X \to Y})
\\
\phi_t &= \operatorname{P}(I_{X \to Y,t}|I_{X \to Y},O_Y)
\\
\operatorname{E}[I_t] &= R_t \sum_{s=1}^t I_{t-s}\omega_s \\
\\
\operatorname{E}[O_t] &= \psi\sum_{u=1}^t \operatorname{E}[I_{t-u}]\phi_u \\
\\
\operatorname{E}[O_t] &= \psi\sum_{u=1}^t \Big(
R_{t-u} \sum_{s=1}^{t-u} I_{t-u-s}\omega_s
\Big)
\phi_u \\
\omega_{t \le 0} &= 0 \\
I_{t \leq 0} &= 0 \\
\phi_{t \leq 0} &= 0 \\
\operatorname{E}[O_t] &= \psi
\sum_{v=1}^{t-1}
  I_{v}
  \sum_{w=1}^{t-v} R_{t-w}\phi_{w}\omega_{v-w}
\\
\operatorname{E}[O_{t+1}] &= \psi
\sum_{v=1}^{t}
  I_{v}
  \sum_{w=1}^{t+1-v} R_{t-w}\phi_{w}\omega_{v-w}
\\
\operatorname{E}[O_{t+1}]-\operatorname{E}[O_t] &= I_tR_{t-1}\phi_1\sum_{v=1}^{t}\omega_v
\end{aligned}
$$