---
title: "ventilator survival models"
author: "Rob Challen"
date: "14 April 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(readxl)
library(tidyverse)
library(lubridate)
devtools::load_all("~/Git/uk-covid-datatools/")
devtools::load_all("~/Git/standard-print-output/")
source("~/Git/uk-covid-datatools/data-raw/rawDataFunctions.R")
library(survival)
library(patchwork)

paths=list(
  chess="~/S3/encrypted/15Apr/CHESS COVID19 CaseReport 20200415.csv",
  lineList="~/S3/encrypted/15Apr/Anonymised Line List 20200415.xlsx",
  ff100="~/S3/encrypted/15Apr/Anonymised Line List 20200415.xlsx",
  chessSummary="~/S3/encrypted/15Apr/CHESS Aggregate Report 20200415.csv",
  sitrep="~/S3/encrypted/8Apr/Covid sitrep report incl CIC 20200408 FINAL.xlsx"
)


ggplot2::theme_set(standardPrintOutput::defaultFigureLayout())
CHESSClean = getCHESS(paths$chess) %>% cleanseCHESSData("2020-04-15")
```




## Survival model - Admission to outcome

```{r}
#unique(CHESS$finaloutcome)

admissionToDischargeOrDeath = CHESSClean %>% filter(age>10) %>% generateSurvivalData(
    hospitaladmissiondate, 
    outcomedate, 
    outcomeExpr = !is.na(finaloutcome),
    ageBreaks = c(-Inf,30,60,80,Inf), 
    ageLabels = c("10-30","30-60","60-80","80+"),
    ageReferenceCat = "30-60"
) %>% select(
    caseid, status, finaloutcome, time, ageCat, sex, left, right
)


fitByAgeCat = survfit(Surv(time,status) ~ ageCat, admissionToDischargeOrDeath)
plot = survminer::ggsurvplot(
  fitByAgeCat, pval=TRUE, conf.int = TRUE
)+ylab("probability still inpatient")

(plot$plot+standardPrintOutput::defaultFigureLayout()) %>% 
  standardPrintOutput::saveThirdPageFigure("~/Dropbox/covid19/ventilator-demand/parameterisation/admission-to-discharge/Fig1_kaplanMeierByAge")

# summary(admissionToDischargeOrDeath)

survModel = coxph(Surv(time,status) ~ sex + age, admissionToDischargeOrDeath %>% rename(age=ageCat))
# survModel %>% gtsummary::tbl_regression(exp = TRUE) 

survminer::ggforest(survModel, data=admissionToDischargeOrDeath %>% rename(age=ageCat) ) %>% 
  standardPrintOutput::saveThirdPageFigure("~/Dropbox/covid19/ventilator-demand/parameterisation/admission-to-discharge/Fig2_coxModel")
```

```{r}
# fitBySex = survfit(Surv(time,status) ~ sex, data=admissionToDischargeOrDeath)
# survminer::ggsurvplot(
#   fitBySex, pval=TRUE, conf.int = TRUE
# )+ylab("probability still inpatient")
# 
# 
# 
# suppressWarnings({
#   referenceGroup = survfit(Surv(time,status) ~ 1, data = admissionToDischargeOrDeath %>% filter(ageCat == "30-60" & sex == "Male"))
#   survminer::ggsurvplot(
#     referenceGroup, pval=TRUE, conf.int = TRUE
#   )+ylab("probability still inpatient")
# })
```

## Parameter fitting

```{r}
censoredAdmissionToDischargeOrDeath = generateSurvivalData(
    CHESSClean %>% filter(age>15), 
    hospitaladmissiondate, 
    outcomedate, 
    outcomeExpr = !is.na(finaloutcome),
    #ageBreaks = c(-Inf,30,60,80,Inf), 
    #ageLabels = c("10-30","30-60","60-80","80+"),
    #ageReferenceCat = "30-60"
) %>% select(
    age, ageCat, left, right
)
```

### Parameter fitting goodness of fit

```{r}
models = c("weibull","gamma","lnorm") #,"pois","norm")
subGroup = censoredAdmissionToDischargeOrDeath %>% filter(ageCat=="40-44") %>% select(left,right) %>% as.data.frame()
dists = suppressWarnings(lapply(models, function(m) fitdistrplus::fitdistcens(subGroup, m)))
#names(dists) = models
p1 = fitdistrplus::qqcompcens(dists, plotstyle = "ggplot") +standardPrintOutput::narrowAndTall()
p2 = fitdistrplus::ppcompcens(dists, plotstyle = "ggplot") +standardPrintOutput::narrowAndTall()
(p1 + p2 + patchwork::plot_layout(ncol=2)) %>% standardPrintOutput::saveQuarterPageFigure("~/Dropbox/covid19/ventilator-demand/parameterisation/admission-to-discharge/Fig3_fitDistributions")


```



```{r}

out = censoredAdmissionToDischargeOrDeath %>% group_by(ageCat) %>% group_modify( function(d,g,...) {
  
  models = c("weibull","gamma","lnorm") #,"pois","norm")
  dists = lapply(models, function(m) suppressWarnings(fitdistrplus::fitdistcens(d %>% as.data.frame(), m)))
  names(dists) = models
  
  params = tibble(
    model = as.vector(t(matrix(c(models,models),nrow=3))), 
    param = as.vector(sapply(sapply(dists, "[", "estimate"), "names")), 
    value = as.vector(unlist(sapply(dists, "[", "estimate"))),
    low_ci = as.vector(sapply(lapply(dists,confint), "[", , 1)),
    high_ci = as.vector(sapply(lapply(dists,confint), "[", , 2))
  )
  
  return(
    tibble(
      model = models,
      n = unlist(sapply(dists, "[", "n")),
      aic = unlist(sapply(dists, "[", "aic")),
      bic = unlist(sapply(dists, "[", "bic")),
      loglik = unlist(sapply(dists, "[", "loglik"))
    ) %>% left_join(params, by="model")
  )
   
})

out %>% mutate(value = sprintf("%1.4f [%1.4f; %1.4f]", value, low_ci, high_ci)) %>% select(ageCat,n,model,aic,bic,loglik,param, value) %>% 
  group_by(ageCat,n,model,aic,bic,loglik) %>% standardPrintOutput::saveTableLandscape("~/Dropbox/covid19/ventilator-demand/parameterisation/admission-to-discharge/SuppTable1_fullBreakdownFittedModels")
```

```{r}
out %>% filter(model=="lnorm") %>% ungroup() %>% mutate(value = sprintf("%1.4f [%1.4f; %1.4f]", value, low_ci, high_ci)) %>%
  select(-low_ci,-high_ci) %>% 
  pivot_wider(names_from = param, values_from = value) %>% select(
  -model,-bic,-aic,age=ageCat, N = n, `log(likelihood)`=loglik, `log(mean) [95% CrI]` = meanlog, `log(sd) [95% CrI]` = sdlog
  ) %>% standardPrintOutput::saveTable("~/Dropbox/covid19/ventilator-demand/parameterisation/admission-to-discharge/Table1_logNormalParameterisation")



```

# 

```{r}
doPdf = function(model, paramNames, params,days=30) {
  names(params) = paramNames
  params$x=0:30
  pred = do.call(paste0("d",model),params)
  return(pred)
}

doCdf = function(model, paramNames, params, days=30) {
  names(params) = paramNames
  params$q=0:30
  pred = do.call(paste0("p",model),params)
  return(pred)
}

doMedian = function(model, paramNames, params, days=30) {
  suppressWarnings({names(params) = paramNames})
  params$p=0.5 #c(0.025,0.05,0.25,0.5,0.75,0.95,0.975)
  pred = do.call(paste0("q",model),params)
  return(pred)
}

doEstimate = function(d, model, pdf=FALSE) {
  out = list()
  
  if (pdf) {
    
    out$pred = doPdf(model, d$param, d$value)
    out$pred_low = doPdf(model, d$param, d$low_ci)
    out$pred_high = doPdf(model, d$param, d$high_ci)
    
  } else {
    
    out$pred = doCdf(model, d$param, d$value)
    out$pred_low = doCdf(model, d$param, d$low_ci)
    out$pred_high = doCdf(model, d$param, d$high_ci)
  }
  
  out$median = doMedian(model, d$param, d$value)
  out$median_low = doMedian(model, d$param, d$low_ci)
  out$median_high = doMedian(model, d$param, d$high_ci)
  return(out)
  
}
```

```{r}
#glimpse(out)
out_sm = out %>% ungroup() %>% group_by(model,param) %>% group_modify(function(d,g,...) {
  
  return(tibble(
    ageCat = d$ageCat,
    value = ksmooth(1:length(d$value), d$value, n.points = length(d$value), bandwidth=2)$y,
    low_ci = ksmooth(1:length(d$value), d$low_ci, n.points = length(d$value), bandwidth=2)$y,
    high_ci = ksmooth(1:length(d$value), d$high_ci, n.points = length(d$value), bandwidth=2)$y
  ))
})

tmp2 = out_sm %>% ungroup() %>% group_by(ageCat, model) %>% group_modify(function (d,g,...) {
  est = suppressWarnings(doEstimate(d, model = g$model)) #, pdf=TRUE))
  return(tibble(x=0:30,y=est$pred, ymin=est$pred_high, ymax=est$pred_low))
})

#ggplot(tmp2 %>% filter(model=="lnorm"),aes(x=x,y=1-y, ymin=1-ymin, ymax=1-ymax,colour=ageCat, fill=ageCat))+geom_line()+geom_ribbon(size = 0,alpha=0.2)+facet_wrap(vars(ageCat))

# surf= ggplot(tmp2 %>% filter(model=="lnorm"),
#   aes(x=x,y=ageCat,z=1-y, fill=1-y, label=sprintf("%1.2f",1-y)))+geom_tile()+scale_fill_gradient2(high="red",mid="yellow",low="green", midpoint=0.5, name="probability\ninpatient",limits=c(0,1))+xlab("days after admission")+ylab("age")+
#   geom_text(angle=90,size=1.8)
#   
# 
# surf %>% standardPrintOutput::saveThirdPageFigure("~/Dropbox/covid19/ventilator-demand/parameterisation/admission-to-discharge/Fig4_losDensity")
# 
# ggplot(tmp2 %>% filter(model=="lnorm"),
#   aes(x=x,y=as.integer(ageCat),z=1-y, label=sprintf("%1.2f",1-y)))+#scale_fill_gradient2(high="red",mid="yellow",low="green", midpoint=0.5, name="probability\ninpatient",limits=c(0,1))+xlab("days after admission")+ylab("age")+
#   #geom_text(angle=90,size=1.8)
#   geom_contour_filled()+scale_y_continuous(
#     breaks = 4:17,
#     labels = c('15-19','20-24','25-29','30-34','35-39','40-44','45-49','50-54','55-59','60-64','65-69','70-74','75-79','80+'))


surf1 = ggplot(tmp2 %>% filter(model=="lnorm"),
  aes(x=x,y=as.integer(ageCat),z=1-y, fill=1-y))+geom_tile()+scale_fill_gradient2(high="red",mid="yellow",low="green", midpoint=0.5, name="probability\ninpatient",limits=c(0,1))+xlab("days after admission")+ylab("age")+
  metR::geom_contour2(colour="black", breaks=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))+scale_y_continuous(
    breaks = 4:17,
    labels = c('15-19','20-24','25-29','30-34','35-39','40-44','45-49','50-54','55-59','60-64','65-69','70-74','75-79','80+'))+
  metR::geom_contour2(colour="blue", breaks=c(0.5), size=1.5)+
  metR::geom_text_contour(breaks=c(0.1,0.3,0.5,0.7,0.9),stroke=0.2)+guides(fill="none")

surf_lo = ggplot(tmp2 %>% filter(model=="lnorm"),
  aes(x=x,y=as.integer(ageCat),z=1-ymax, fill=1-ymax))+geom_tile()+scale_fill_gradient2(high="red",mid="yellow",low="green", midpoint=0.5, name="probability\ninpatient",limits=c(0,1))+xlab("days after admission")+ylab("age")+
  metR::geom_contour2(colour="black", breaks=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))+scale_y_continuous(
    breaks = 4:17,
    labels = c('15-19','20-24','25-29','30-34','35-39','40-44','45-49','50-54','55-59','60-64','65-69','70-74','75-79','80+'))+
  metR::geom_contour2(colour="blue", breaks=c(0.5), size=1.5)+
  theme(axis.title=element_blank(),
        axis.text.y=element_blank(),
        axis.text.x=element_blank())+guides(fill="none")

surf_hi = ggplot(tmp2 %>% filter(model=="lnorm"),
  aes(x=x,y=as.integer(ageCat),z=1-ymin, fill=1-ymin))+geom_tile()+scale_fill_gradient2(high="red",mid="yellow",low="green", midpoint=0.5, name="probability\ninpatient",limits=c(0,1))+xlab("days after admission")+ylab("age")+
  metR::geom_contour2(colour="black", breaks=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))+scale_y_continuous(
    breaks = 4:17,
    labels = c('15-19','20-24','25-29','30-34','35-39','40-44','45-49','50-54','55-59','60-64','65-69','70-74','75-79','80+'))+
  metR::geom_contour2(colour="blue", breaks=c(0.5), size=1.5)+
  theme(axis.title=element_blank(),
        axis.text.y=element_blank(),
        axis.text.x=element_blank()
        )+guides(fill="none")

surf = surf1 + (surf_lo / surf_hi) + patchwork::plot_annotation(tag_levels = 'A') + patchwork::plot_layout(ncol=2,widths = c(2,1))

surf %>% standardPrintOutput::saveHalfPageFigure("~/Dropbox/covid19/ventilator-demand/parameterisation/admission-to-discharge/Fig4_losDensity")

# ggplot(tmp2 %>% filter(model=="lnorm"),
#   aes(x=x,y=ageCat, fill=ymin, label=sprintf("%1.2f",y)))+geom_tile()+scale_fill_gradient2(high="green",mid="yellow",low="red", midpoint=0.5)+
#   geom_text(angle=90,size=2.5)
# 
# ggplot(tmp2 %>% filter(model=="lnorm"),
#   aes(x=x,y=ageCat, fill=ymax, label=sprintf("%1.2f",y)))+geom_tile()+scale_fill_gradient2(high="green",mid="yellow",low="red", midpoint=0.5)+
#   geom_text(angle=90,size=2.5)

```


```{r}
# tmp3 = out_sm %>% ungroup() %>% group_by(ageCat, model) %>% group_modify(function (d,g,...) {
#   est = doEstimate(d, model = g$model) #, pdf=TRUE)
#   #browser()
#   return(tibble(x=g$ageCat,y=est$median, ymin=est$median_low, ymax=est$median_high))
# }) %>% mutate(ymin=if_else(is.nan(ymin),0,ymin))
# 
# mlos = ggplot(tmp3 %>% filter(model=="lnorm"),
#        aes(x=x,y=y, ymin=ymin, ymax=ymax, group=1))+geom_line(stat = "smooth")+geom_ribbon(aes(x=x,ymin=smooth(ymin), ymax=smooth(ymax), group=1),size = 0,alpha=0.2)+ylim(c(0,20))+xlab("age")+ylab("median length of stay")+standardPrintOutput::narrowAndTall()
# 
# mlos %>% standardPrintOutput::saveSixthPageFigure("~/Dropbox/covid19/ventilator-demand/parameterisation/admission-to-discharge/Fig5_losMedianCrInt")

```


# Other parameters
## Admission to Hospital to Admission to ITU

```{r}
# admissionToItu = CHESSdf %>% mutate(
#     status = if_else(is.na(finaloutcomedate),0,1),
#     outcomedate = as.Date(if_else(is.na(finaloutcomedate),CHESS_date,finaloutcomedate)),
#     timeToTest = as.numeric(labtestdate - hospitaladmissiondate),
#     age = ageyear+agemonth/12,
#     time = as.numeric(dateadmittedicu - hospitaladmissiondate)
#   ) %>% filter(
#     !is.na(time) & timeToTest < 10 & time>0 & sex != "Unknown" & age > 10
#   ) %>% mutate(
#     ageCat = cut(ageyear,breaks = c(-Inf,30,60,80,Inf), labels = c("10-30","30-60","60-80","80+")), 
#     sex = as.factor(sex),
#     finaloutcome = as.factor(finaloutcome)
#   ) %>% mutate(
#     ageCat = relevel(ageCat, ref = "30-60"),
#     sex = relevel(sex, ref="Male")
#   ) %>%
#   filter() %>%
#   select(caseid, status, finaloutcome, time, age, ageCat, sex)
# 
# admToItuSurvModel = coxph(Surv(time,status) ~ sex + ageCat, admissionToItu)
# summary(admToItuSurvModel)
```

