---
title: "Growth rate by LTLA"
author: "Rob Challen"
date: '`r format(Sys.Date(), "%d-%m-%Y")`'
output:
  beamer_presentation:
    slide_level: 2
    theme: "Singapore"
    colortheme: "seagull"
    fig_width: 12
    fig_height: 5
classoption: "aspectratio=169"
fontsize: 10pt
knit: (function(inputFile, encoding,...) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = paste0("~/Dropbox/covid19/current-rt/",Sys.Date()), output_file=paste0('growth-rate-map-',Sys.Date(),'.pdf')) })
# output: 
#   ioslides_presentation:
#     widescreen: true
#     smaller: true
#     css: ~/Git/uk-covid-datatools/vignettes/ioslides.css
#     # self_contained: false
#     # lib_dir: ~/Dropbox/covid19/current-rt/data/libs
# knit: (function(inputFile, encoding,...) {
#   rmarkdown::render(inputFile, encoding = encoding, output_dir = "~/Dropbox/covid19/current-rt/data", output_file=paste0('current-rt-data-',Sys.Date(),'.html')) })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

devtools::load_all("~/Git/standard-print-output/")
standardPrintOutput::setDefaults()
setwd("~/Git/uk-covid-datatools/vignettes/")
library(tidyverse)
library(patchwork)
devtools::load_all("~/Git/uk-covid-datatools/")
ukcovidtools::setup()
ggplot2::theme_set(standardPrintOutput::defaultFigureLayout())
standardPrintOutput::setDefaults()
```

```{r}
## Get data -----


map = dpc$getDaily("LAD-GROWTH-MAP", orElse = function() {
  ageBreaks = c(6,18,23,60,75);
  
  # events = dpc$datasets$getSignificantDates(nocache=TRUE) %>% 
  #   filter(Label %in% c("Lockdown","VE day","Hotels and bars reopen","Relaxation shielding","Shielding ends (excl Wales)","End summer term","Start autumn term","Start univerity term","England 2nd lockdown","England tier system"))
  # 
  # events2 = dpc$datasets$getSignificantDates(nocache=TRUE) %>% 
  #   filter(Label %in% c("Start autumn term","Start univerity term","Testing capacity limited","England 2nd lockdown","School half term","England tier system"))
  # 
  # events3 = dpc$datasets$getSignificantDates(nocache=TRUE) %>% 
  #   filter(Label %in% c("Start autumn term","North West England tier 3","School half term","England 2nd lockdown","England tier system"))
  # 
  # events4 = dpc$datasets$getSignificantDates(nocache=TRUE) %>% 
  #   filter(Label %in% c("Lockdown","Hotels and bars reopen","Start autumn term","England 2nd lockdown","England tier system"))
  
  dmg = dpc$demog$getDemographicsForShape(mapId = "LAD19",ageBreaks = ageBreaks, combineGenders = TRUE)
  
  tmp = dpc$spim$getLineListIncidence(ageBreaks = ageBreaks, codeTypes = "LAD",subgroup=asymptomatic_indicator) %>% 
    filter(ageCat !="unknown" & subgroup!="Y") %>% mutate(ageCat=as.character(ageCat)) %>%
    tsp$aggregateGender() %>% tsp$aggregateSubgroup() %>% inner_join(dmg %>% mutate(ageCat=as.character(ageCat)), by=c("code","ageCat"), suffix=c("","rhs")) %>% rename(population=count)
  
  tmp = tmp %>% filter(ageCat  != "<6") 
  all = tmp %>% tsp$aggregateAge() %>% mutate(ageCat="all")
  
  tmp2 = bind_rows(
    tmp,all
  ) %>% mutate(ageCat = factor(ageCat,levels=c("6-17","18-22","23-59","60-74","75+","all"),ordered=TRUE))
  
  casesGeog = tmp2 %>% tsp$logIncidenceStats(growthRateWindow = 7)
  

 return(dpc$geog$getMap("LAD19") %>% rmapshaper::ms_simplify(keep = 0.025) %>% inner_join(casesGeog %>% select(-name,-codeType), by=c("code")) %>% ungroup() %>% sf::st_as_sf())
})
```


```{r}

mapSGene = dpc$getDaily("LAD-SGENE-MAP", nocache=TRUE, orElse = function() {
  
  ageBreaks = c(6,18,23,60,75);
  tmpSNeg = dpc$spim$getSDropoutFreqency(codeTypes = "LAD",ageBreaks = ageBreaks,window=14)
  tmpSNegAll = dpc$spim$getSDropoutFreqency(codeTypes = "LAD",window=14) %>% mutate(ageCat="all")
  tmpSNeg = bind_rows(tmpSNeg %>% filter(ageCat != "<6"),tmpSNegAll) 
  
  dmg = dpc$demog$getDemographicsForShape(mapId = "LAD19",ageBreaks = ageBreaks, combineGenders = TRUE)
  dmgAll = dpc$demog$getDemographicsForShape(mapId = "LAD19",ageBreaks = c(), combineGenders = TRUE)  %>% mutate(ageCat="all")
  
  dmg = bind_rows(dmg %>% filter(ageCat != "<6"),dmgAll) 
  
  tmpSNeg2 = tmpSNeg %>% inner_join(dmg %>% ungroup() %>% select(-name) %>% mutate(ageCat=as.character(ageCat)) %>% rename(population=count), by=c("code","ageCat"), suffix=c("",".rhs"))
  
  tmpSNeg2 = tmpSNeg2 %>% mutate(ageCat = factor(ageCat,levels=c("6-17","18-22","23-59","60-74","75+","all"),ordered=TRUE))
  out = dpc$geog$getMap("LAD19") %>% rmapshaper::ms_simplify(keep = 0.025) %>% inner_join(tmpSNeg2 %>% ungroup() %>% select(-name,-codeType), by=c("code")) %>% ungroup() %>% sf::st_as_sf()
  return(out)
  
})

```

```{r}



slider = function(progression, minDate, maxDate = Sys.Date(),events = dpc$datasets$getSignificantDates() %>% filter(Significance==1)) {
  dates = tibble::tibble(progress = as.Date(progression,origin="1970-01-01"))
  england = dpc$datasets$getPHEApiNations() %>% filter(name=="England" & statistic=="case" & date >= minDate & date <= maxDate)
  england = england %>% ungroup() %>% tsp$logIncidenceStats()
  return(ggplot(dates,aes(xmin=progress,xmax=progress+1))+
    geom_vline(mapping=aes(xintercept=`Start date`,colour=Label),data=events)+
    geom_rect(colour="red",ymin=0,ymax=Inf)+
    geom_line(data=england,mapping=aes(x=date,y=Est.value),inherit.aes = FALSE)+
    #scale_y_continuous(trans="log1p")+
    standardPrintOutput::hideY()+
    scale_x_date(date_breaks = "1 month",date_labels = "%b")+
    #guides(col=guide_legend(direction="horizontal",nrow=1,title.theme = element_blank(),label.theme = element_text(size = 12)))+
    theme(
      axis.text.x = element_text(angle=0,hjust=0.5,size=6),
      axis.title.x = element_blank(),
      axis.ticks.y = element_blank(),
      legend.position = "bottom",
      legend.direction = "horizontal",
      legend.title = element_blank(),
      legend.text =  element_text(size = 6)
    ))
}
#slider("2021-01-01",minDate="2020-03-01")
```


```{r}
maxDate = min((mapSGene %>% as.data.frame() %>% pull(date) %>% max()),(map %>% as.data.frame() %>% pull(date) %>% max()))
minDate = max((mapSGene %>% as.data.frame() %>% pull(date) %>% min()),(map %>% as.data.frame() %>% pull(date) %>% min()))

nDates = map %>% as.data.frame() %>% pull(date) %>% unique() %>% length()

dates = seq(minDate,maxDate,by = 2)

## define plot functions ----

growthMapForDate = function(maxDate = max(map$date), anim=FALSE, longs = c(NA,NA), lats = c(NA,NA)) {
  tmp = map %>% filter(ageCat!="all")
  if(!anim) tmp = tmp %>% filter(date==maxDate)
  p=ggplot(tmp) + 
    geom_sf(aes(fill=Growth.windowed.value),size = 0.05) + 
    facet_wrap(vars(ageCat), ncol = 5) + 
    standardPrintOutput::defaultMapLayout() + 
    standardPrintOutput::narrower() + 
    coord_sf(xlim = longs, ylim=lats) +
    scale_fill_distiller(palette = "RdGy", name="growth rate", oob=scales::squish, lim=c(-0.10,0.10))
  s = slider(progression = tmp$date,minDate = minDate)
  #if (!anim) p = p+labs(title=maxDate)
  return(p+s+patchwork::plot_layout(ncol=1,heights=c(10,1)))
}

growthMapForDate() #,longs=c(-0.2,0.1), lats=c(51,51.3))
#p3 %>% standardPrintOutput::saveTwoThirdPageFigure("~/Dropbox/covid19/by-age/CaseGrowthByAgeAndLAD")
```

```{r}
probPosMapForDate = function(maxDate = max(map$date),anim = FALSE, longs = c(NA,NA), lats = c(NA,NA)) {
  tmp = map %>% filter(ageCat!="all")
  if(!anim) tmp = tmp %>% filter(date==maxDate)
  p=ggplot(tmp) + 
    geom_sf(aes(fill=Growth.windowed.ProbPos.value),size = 0.05) + 
    facet_wrap(vars(ageCat), ncol = 5) + 
    standardPrintOutput::defaultMapLayout() + 
    standardPrintOutput::narrower() + 
    coord_sf(xlim = longs, ylim=lats) +
    scale_fill_distiller(palette = "RdYlGn", name="P(r>0)",lim = c(0,1))
  s = slider(progression = tmp$date,minDate = minDate)
  #if (!anim) p = p+labs(title=maxDate)
  return(p+s+patchwork::plot_layout(ncol=1,heights=c(10,1)))
}

probPosMapForDate(maxDate)
```

```{r}
sGeneMapForDate = function(maxDate = max(mapSGene$date),anim = FALSE, longs = c(NA,NA), lats = c(NA,NA)) {
  tmp = mapSGene %>% filter(ageCat!="all" & sGene=="Negative")
  if(!anim) tmp = tmp %>% filter(date==maxDate)
  p=ggplot(tmp) + 
    geom_sf(aes(fill=Roll.mean),size = 0.05) + 
    facet_wrap(vars(ageCat), ncol = 5) + 
    standardPrintOutput::defaultMapLayout() + 
    standardPrintOutput::narrower() + 
    coord_sf(xlim = longs, ylim=lats) +
    scale_fill_distiller(palette = "RdYlBu", name="P(S-)",lim = c(0,1))
  s = slider(progression = tmp$date,minDate = minDate)
  #if (!anim) p = p+labs(title=maxDate)
  return(p+s+patchwork::plot_layout(ncol=1,heights=c(10,1)))
}

sGeneMapForDate(maxDate)
```


```{r}

compositeMapForDate = function(maxDate = max(map$date), anim=FALSE, longs = c(NA,NA), lats = c(NA,NA)) {
  tmp = map %>% filter(ageCat=="all")
  
  if(!anim) tmp = tmp %>% filter(date==maxDate)
  p1=ggplot(tmp) + 
    geom_sf(aes(fill=Growth.windowed.value),size = 0.05) + 
    standardPrintOutput::defaultMapLayout() + 
    standardPrintOutput::narrower() + 
    coord_sf(xlim = longs, ylim=lats) +
    scale_fill_distiller(palette = "RdGy", name="growth rate", oob=scales::squish, lim=c(-0.10,0.10))

  p2=ggplot(tmp) + 
    geom_sf(aes(fill=Growth.windowed.ProbPos.value),size = 0.05) + 
    standardPrintOutput::defaultMapLayout() + 
    standardPrintOutput::narrower() + 
    coord_sf(xlim = longs, ylim=lats) +
    scale_fill_distiller(palette = "RdYlGn", name="P(r>0)",lim = c(0,1))

  tmp2 = mapSGene %>% filter(ageCat=="all" & sGene=="Negative")
  if(!anim) tmp2 = tmp2 %>% filter(date==maxDate)
  p3=ggplot(tmp2) + 
    geom_sf(aes(fill=Roll.mean),size = 0.05) + 
    standardPrintOutput::defaultMapLayout() + 
    standardPrintOutput::narrower() + 
    coord_sf(xlim = longs, ylim=lats) +
    scale_fill_distiller(palette = "RdYlBu", name="P(S-)",lim = c(0,1))
  
  s = slider(progression = tmp$date,minDate = minDate)
  #if (!anim) p = p+labs(title=maxDate)
  return((p1|p2|p3)/s+patchwork::plot_layout(ncol=1,heights=c(10,1)))
}

compositeMapForDate(maxDate)

```

```{r}
directory = "~/Dropbox/covid19/lockdown2-impact/maps"
minDate = as.Date("2021-01-30")
dates = seq(minDate,maxDate,by = 2)
# dates = seq(maxDate-4,maxDate,by = 2)

for(i in dates) {
  date = as.Date(i,"1970-01-01")
  
  ggsave(
    filename=glue::glue("{directory}/composite/England-{date}.png"),
    plot=compositeMapForDate(date),
    width = 10,
    height = 5,
    units = "in"
  )
}

for(i in dates) {
  date = as.Date(i,"1970-01-01")
  
  ggsave(
    filename=glue::glue("{directory}/growth/England-{date}.png"),
    plot=growthMapForDate(date),
    width = 10,
    height = 5,
    units = "in"
  )

}
  
for(i in dates) {
  date = as.Date(i,"1970-01-01")
  
  ggsave(
    filename=glue::glue("{directory}/prob-positive/England-{date}.png"),
    plot=probPosMapForDate(date),
    width = 10,
    height = 5,
    units = "in"
  )

}
  
for(i in dates) {
  date = as.Date(i,"1970-01-01")

  ggsave(
    filename=glue::glue("{directory}/s-gene/England-{date}.png"),
    plot=sGeneMapForDate(date),
    width = 10,
    height = 5,
    units = "in"
  )
}
  


```

```{r, echo = FALSE, results = "asis"}
for(i in dates) {
  date = as.Date(i,"1970-01-01")
  cat("\n\n## Date = ", as.character(date), "\n\n")
  print(growthMapForDate(date))
}

```


```{r, echo = FALSE, results = "asis"}

for(i in dates) {
  date = as.Date(i,"1970-01-01")
  cat("\n\n## Date = ", as.character(date), "\n\n")
  print(growthMapForDate(date,longs = c(-1.5, 1.5), lats = c(50.5, 52.25)))
  
}

```

```{r, echo = FALSE, results = "asis"}

for(i in dates) {
  date = as.Date(i,"1970-01-01")
  cat("\n\n## Date = ", as.character(date), "\n\n")
  print(sGeneMapForDate(date))
}

```

```{r, echo = FALSE, results = "asis"}

for(i in dates) {
  date = as.Date(i,"1970-01-01")
  cat("\n\n## Date = ", as.character(date), "\n\n")
  print(compositeMapForDate(date))
}

```

```{r eval=FALSE}
## Server code ----

locs = list(
  "East of England" = list(longs = c(-1, 2), lats = c(51.25, 53.25)),
  "London" = list(longs = c(-0.7, 0.5), lats = c(51.25, 51.75)),
  "Midlands" = list(longs = c(-3.5, 0.5), lats = c(51.5, 53.75)),
  "North East and Yorkshire" = list(longs = c(-2.75, 0.25), lats = c(53.5, 56)),
  "North West" = list(longs = c(-3.75, -1.75), lats = c(52.75, 55.25)),
  "South East" = list(longs = c(-1.5, 1.5), lats = c(50.5, 51.75)),
  "South West" = list(longs = c(-6, -1), lats = c(49.75, 51.75))
)

# Define the UI
library(shiny)
ui = fluidPage(
#   
#   # App title
  titlePanel("Growth rate by unitary authority over time"),

  # Sidebar layout with input and output definitions
  sidebarLayout(

    # Sidebar panel for inputs
    sidebarPanel(
      selectInput(inputId = "Location",
                  label = "Select a region:",
                  choices = list("England" = "England",
                                 "East of England" = "East of England",
                                 "London" = "London",
                                 "Midlands" = "Midlands",
                                 "North East and Yorkshire" = "North East and Yorkshire",
                                 "North West" = "North West",
                                 "South East" = "South East",
                                 "South West" = "South West")),

      

      selectInput(inputId = "Summary",
                  label = "Select statistic:",
                  choices = list("Growth rate" = "Growth",
                                 "P(r) > 0" = "ProbPos"),
                  selected = "Growth"),
      sliderInput(inputId = "Date",
                  label = "Date:",
                  min = minDate,
                  max = maxDate,
                  value = maxDate,
                  step = 7),
    ),

    # Main panel for displaying outputs
    mainPanel(
      plotOutput("map")
    )
  )
)

# Define the server
server = function(input, output) {

  # Create the map
  output$map <- renderPlot({
    loc = locs[[input$Location]]
    if(input$Summary == "ProbPos") {
      probPosMapForDate(input$Date,longs=loc$longs,lats=loc$lats)
    } else {
      growthMapForDate(input$Date,longs=loc$longs,lats=loc$lats)
    }
  }, width=1000,height=800)

  #output$map <- renderGirafe({
  #  ggiraph(code = print(createMap(r0shapes, input$Location, input$Date)), width_svg = 8, height_svg = 8)
  #})

}

# Finally, we can run our app by either clicking "Run App" in the top of our RStudio IDE, or by running
shinyApp(ui = ui, server = server)
```

```{r eval=FALSE}
## Amination code ----



ll = dpc$spim$getLineList()
#ll %>% filter(LTLA_code == "E06000001") %>% group_by(specimen_date,asymptomatic_indicator) %>% count() %>% pivot_wider(names_from=asymptomatic_indicator, values_from = n) %>% View()


ltla = dpc$spim$getLineListIncidence(specimenOrReport = "specimen", codeTypes = c("NHSER","LAD"),subgroup = asymptomatic_indicator) %>%
  filter(codeType %in% c("NHSER","LAD") & subgroup!="Y") %>% 
      tsp$aggregateAge() %>% 
      tsp$aggregateGender() %>% 
      tsp$aggregateSubgroup() %>%
      dpc$demog$findDemographics()

ltla2 = ltla %>% tsp$logIncidenceStats(growthRateWindow = 14, smoothingWindow = 14)
# Get NHSER parent for each LTLA 
ltla3 = ltla2 %>% tsp$codes$parentCode(parentCodeTypes = "NHSER")


# Tier data
jun = dpc$fileProvider("juniper")
# jun$listFiles("tiers")
tidyOut = readr::read_csv(jun$getFile("tiers/tidyLAD19Tiers-2020-12-14.csv"))

ltla4 = ltla3 %>% left_join(tidyOut %>% select(-name,-codeType), by=c("code","date"))
ltla4$tier = factor(ltla4$tier, levels=c("none","one","one+","two","two+","local","three","three+","lockdown"),ordered=TRUE)



ltlaByTier = ltla4 %>% filter(codeType!="NHSER" & name!="Unknown (England)") %>% group_by() %>% arrange(code,date)
pal = c("none"="#D0D0D0","one"="#A0A0A0","one+"="#40C040","two"="#6060C0","two+"="#4040C0","local"="#C08080","three"="#C06060","three+"="#C04040","lockdown"="#404040")

plotDates = c(as.Date(c("2020-08-14","2020-09-14","2020-10-07","2020-11-02","2020-11-23")),max(ltlaByTier$date))
dates = tibble::tibble(progress = seq(min(ltla$date),max(ltla$date),1))

## Animation by region ----

animBase = ggplot(
  ltlaByTier %>% 
    #filter(date == max(date)) %>%
    filter(!is.na(parentCode)), # There are some missing here
    aes(x=Growth.windowed.value, y=Est.value/population*1000000,size=population,colour=parentName),alpha=0.8) + 
  geom_vline(xintercept = 0, colour="grey40")+
  geom_point() + #alpha=0.2) + 
  ylab("Symptomatic covid per 1M per day")+
  xlab("7 day growth rate")+
  scale_size_area(max_size=3,guide="none")+
  scale_y_continuous(trans="log1p", breaks=c(0,2,5,20,50,200,500,2000,5000)) +
  scale_alpha_manual(values = c(1,0.3), guide="none") +
  scale_colour_brewer(palette = "Dark2", name="Region")+#facet_wrap(vars(parentName))+#, oob=scales::squish, lim=c(-0.10,0.10))+
  coord_cartesian(xlim=c(-0.25,0.25))+
  #guides(col=guide_legend(direction="horizontal",nrow=1,title.theme = element_blank(),label.theme = element_text(size = 12)))+
  theme(
    axis.text = element_text(size = 12),
    axis.text.x = element_text(angle=0,hjust=0.5),
    axis.title = element_text(size = 14),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.title = element_blank(),
    legend.text =  element_text(size = 12)
    )

anim = animBase +
  gganimate::transition_time(date)+
  gganimate::enter_fade() +
  gganimate::exit_fade()


mainGif = gganimate::animate(anim, renderer=gganimate::magick_renderer(), width=600, height=600, nframes=dates %>% nrow())

## Animation By tier ----

dates = tibble::tibble(progress = seq(min(ltla$date),max(ltla$date),1))


animTier = ggplot(
  ltlaByTier %>% 
    #filter(date == max(date)) %>%
    #filter(date == "2020-03-20") %>%
    filter(!is.na(parentCode)), # There are some missing here
    aes(x=Growth.windowed.value, y=Est.value/population*1000000,size=population,colour=tier),alpha=0.8) + 
  geom_vline(xintercept = 0, colour="grey40")+
  geom_point() + #alpha=0.2) + 
  ylab("Symptomatic covid per 1M per day")+
  xlab("7 day growth rate")+
  scale_size_area(max_size=3,guide="none")+
  scale_y_continuous(trans="log1p", breaks=c(0,2,5,20,50,200,500,2000,5000)) +
  scale_alpha_manual(values = c(1,0.1), guide="none") +
  scale_color_manual(values = pal)+
  #scale_colour_brewer(palette="Reds" ,na.value="grey80")+
  #scale_colour_viridis_d(direction = -1,na.value="grey80")+
  coord_cartesian(xlim=c(-0.25,0.25))+
  #guides(col=guide_legend(direction="horizontal",nrow=1,title.theme = element_blank(),label.theme = element_text(size = 12)))+
  theme(
    axis.text = element_text(size = 12),
    axis.text.x = element_text(angle=0,hjust=0.5),
    axis.title = element_text(size = 14),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.title = element_blank(),
    legend.text =  element_text(size = 12)
    )

anim2 = animTier +
  gganimate::transition_time(date)+
  gganimate::enter_fade() +
  gganimate::exit_fade()

lockdownGif = gganimate::animate(anim2, renderer=gganimate::magick_renderer(), width=600, height=600, nframes=dates %>% nrow())

## Timeline animation ----

events = dpc$datasets$getSignificantDates() %>% filter(Significance==1)

england = dpc$datasets$getPHEApiNations() %>% filter(name=="England" & statistic=="case" & date >= min(dates$progress) & date <= max(dates$progress))
england = england %>% ungroup() %>% tsp$logIncidenceStats()

slider= ggplot(dates,aes(xmin=progress,xmax=progress+1))+
  geom_vline(mapping=aes(xintercept=`Start date`,colour=Label),data=events)+
  geom_rect(colour="red",ymin=0,ymax=Inf)+
  geom_line(data=england,mapping=aes(x=date,y=Est.value),inherit.aes = FALSE)+
  #scale_y_continuous(trans="log1p")+
  standardPrintOutput::hideY()+
  scale_x_date(date_breaks = "1 month",date_labels = "%b")+
  #guides(col=guide_legend(direction="horizontal",nrow=1,title.theme = element_blank(),label.theme = element_text(size = 12)))+
  theme(
    axis.text.x = element_text(angle=0,hjust=0.5,size=12),
    axis.title.x = element_blank(),
    axis.ticks.y = element_blank(),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.title = element_blank(),
    legend.text =  element_text(size = 12)
  )
#slider = slider+geom_rect(mapping = aes(xmin=progress,xmax=progress+1),ymin=-Inf,ymax=Inf,colour="red")

slideAnim = slider + gganimate::transition_time(progress)+
  gganimate::enter_fade() +
  gganimate::exit_fade()

#gganimate::animate(slideAnim, nframes=dates %>% nrow())
timeGif = gganimate::animate(slideAnim, renderer=gganimate::magick_renderer(), width=1200, height=100, nframes=dates %>% nrow())



## composite animation ----

layoutGifs = function(i) {
  magick::image_append(c(
    magick::image_append(c(
      mainGif[i], 
      lockdownGif[i]
    )),
    timeGif[i]), stack=TRUE)
}

new_gif <- layoutGifs(1)
for(i in 2:(dates %>% nrow())){ 
  combined <- layoutGifs(i)
  new_gif <- c(new_gif, combined)
}

magick::image_write_gif(new_gif,path=paste0("~/Dropbox/covid19/current-rt/",Sys.Date(),"/GrowthRatesVsIncidence-",Sys.Date(),".gif"))

```