---
title: "Facebook mobility"
author: "Rob Challen"
date: "27/11/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
devtools::load_all("~/Git/uk-covid-datatools/")
# ukcovidtools::setup()
ukcovidtools::reload()

devtools::load_all("~/Git/standard-print-output/")
standardPrintOutput::setDefaults()
```

```{r}
tmp = config::get()
s3 = fileProvider(tmp$secrets, "juniper")
files = s3$listAllFiles()
prevMap = files %>% filter(path %>% stringr::str_detect("Movement between Administrative Regions")) %>% filter(path %>% stringr::str_detect("\\/\\.",negate = TRUE))
```

```{r}

prevMap = prevMap %>% mutate(
  date = as.Date(path %>% stringr::str_extract("20[0-9]{2}-[0-9]{2}-[0-9]{2}")),
  time = path %>% stringr::str_extract("[0-9]{2}00")
)

prevMap2 = prevMap # %>% filter(date == max(date))

fb = s3$processFiles(paths = prevMap2$path,func = read.csv)
fb2 = fb %>% tidyr::unnest(cols=c(value)) %>% inner_join(prevMap2, by="path")

tmpFrom = bind_rows(
  fb2 %>% filter(country=="GB") %>% select(lon = start_lon, lat = start_lat, name = start_polygon_name, id=start_polygon_id),
  fb2 %>% filter(country=="GB") %>% select(lon = end_lon, lat = end_lat, name = end_polygon_name, id=end_polygon_id)
) %>% group_by(name,lat,lon,id) %>% count() 

tmpFrom %>% write.csv("~/Dropbox/covid19/facebook/facebookPolygons.csv")

```

```{r}

wdShape = dpc$demog$getDemographicsForShape(mapId = "WD11")
wdShape = wdShape %>% group_by(code,name) %>% summarise(count=sum(count))
wdShape = dpc$geog$getMap("WD11") %>% inner_join(wdShape, by=c("code","name"))

tmpFrom2 = tmpFrom %>% as.data.frame() %>% sf::st_as_sf(coords=c("lon","lat"), crs=4326)

map = dpc$geog$createCatchment(supplyShape = tmpFrom2 %>%group_by(name,id), supplyIdVar = id, supplyVar = n,
      demandId = "WD11", 
      demandShape = wdShape,
      demandIdVar = code, 
      demandVar = count,
      outputMap = TRUE
    )
```

```{r}

tmpFrom2 = tmpFrom %>% sf::st_as_sf(coords=c("lon","lat"), crs=4326)
ggplot()+geom_sf(data=dpc$geog$getMap("WD11"))+geom_sf(data=tmpFrom2,colour="red",size=0.5)

leaflet::leaflet() %>% leaflet::addTiles() %>% leaflet::addPolygons(data=map$map) %>% leaflet::addCircleMarkers(data=tmpFrom, lng = tmpFrom$lon, lat = tmpFrom$lat, color = "red")
# Its not a clean mapping from any of LAD, LSOA, MSOA, WD, 

ggplot(map$suppliedArea,aes(fill=as.factor(iteration)))+geom_sf(size=0.05,colour="grey50")+scale_fill_viridis_d()+geom_sf(data=map$map,colour="white",size=0.1,inherit.aes = FALSE,fill=NA)

#mapping = tmpFrom %>% dpc$geog$getContainedIn(outputMapId = "LSOA11",inputIdVar = start_polygon_id, outputIdVar = code) %>% distinct()

mapping %>% inner_join(tmpFrom %>% as.data.frame() %>% select(start_polygon_id,start_polygon_name) %>% distinct() ,by=c("from"="start_polygon_id")) %>% inner_join(dpc$geog$getMap("WD11") %>% as.data.frame() %>% select(name,code),by=c("to"="code"))


```



