---
title: "Vaccination effects"
author: "Rob Challen"
date: '`r format(Sys.Date(), "%d-%m-%Y")`'
output:
  beamer_presentation:
    slide_level: 2
    theme: "Singapore"
    colortheme: "seagull"
classoption: "aspectratio=169"
knit: (function(inputFile, encoding,...) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "~/Dropbox/covid19/vaccination", output_file=paste0('vaccination-',Sys.Date(),'.pdf') ) })
# output: 
#   ioslides_presentation:
#     widescreen: true
#     smaller: true
#     css: ~/Git/uk-covid-datatools/vignettes/ioslides.css
# knit: (function(inputFile, encoding,...) {
#   rmarkdown::render(inputFile, encoding = encoding, output_dir = "~/Dropbox/covid19/by-age", output_file=paste0('covid-demograpics-',Sys.Date(),'.html') ) })
fig_width: 7
fig_height: 5
out.width: "100%"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

devtools::load_all("~/Git/standard-print-output/")
devtools::load_all("~/Git/uk-covid-datatools/")

library(tidyverse)
library(patchwork)
library(rgdal)
library(ggplot2)
library(ggspatial)
library(rgeos)
library(maptools)
library(patchwork)
library(sp)
library(sf)

ggplot2::theme_set(standardPrintOutput::defaultFigureLayout())
standardPrintOutput::setDefaults()
ukcovidtools::setup()


```

## Proportion vaccinated by LTLA

```{r}
devtools::load_all("~/Git/uk-covid-datatools/")
ukcovidtools::reload()
imms = dpc$spim$getImmunizationFraction(ageBreaks = c(50,60,70,80))
```

```{r}
p = ggplot(imms,aes(x=date,y=value,group=paste0(code,subgroup)))+geom_line(alpha=0.1,colour="grey20")+facet_wrap(vars(ageCat),nrow=1)+geom_line(data = imms %>% filter(name=="Hartlepool"),aes(colour=subgroup))

p %>% standardPrintOutput::saveSlideFigure("~/Dropbox/covid19/vaccination/ProgressByLTLA")
```

```{r}

cases = dpc$spim$getLineListIncidence(ageBreaks = c(50,60,70,80),filterExpr = asymptomatic_indicator!="Y", codeTypes = "LAD", subgroup=NULL) %>% tsp$aggregateGender()
#casesLAD = cases %>% tsp$aggregateAge()
#casesLAD = casesLAD %>% tsp$logIncidenceStats(growthRateWindow = 14)
cases = cases %>% tsp$logIncidenceStats(growthRateWindow = 14) %>% tsp$estimateRtQuick(window = 7,valueVar = Est.value)


```


```{r}

goCompare = function(cases, imms, ageCatRef = "70-79", ageCatComp = "80+", refDelay=0, immDelay = c(14,21,28)) {
  
  cases2 = cases %>% 
    left_join(
      imms %>% rename(immunizedPercent=value, immunizedDoses = subgroup) %>% select(code,date,ageCat,immunizedPercent,immunizedDoses), 
      by=c("code","date","ageCat"), suffix=c("",".imm")
    ) %>% mutate(immunizedPercent = ifelse(is.na(immunizedPercent),0,immunizedPercent))
  
  casesRef = cases2 %>% filter(ageCat==ageCatRef)
  cases3 = cases2 %>% filter(ageCat==ageCatComp) %>% 
    inner_join(casesRef, by=c(ukcovidtools::covidStandardJoins("ageCat"),"immunizedDoses"), suffix=c("",".ref")  ) %>%
    mutate(
      immunizedPercent.delta = immunizedPercent-immunizedPercent.ref
    )
  
  leadDf = tibble(refDelay = refDelay) %>% full_join(tibble(immDelay = immDelay), by=character())
  leadDf = leadDf %>% mutate(lead = immDelay, lead.ref = immDelay+refDelay)
  
  cases4 = cases3 %>% ukcovidtools::covidStandardSelect(starts_with("Growth"),`Mean(R)`,`Mean(R).ref`,ageCat.ref,immunizedPercent,immunizedPercent.ref,immunizedPercent.delta,immunizedDoses) %>% 
    full_join(leadDf, by=character()) %>%
    group_by(lead,lead.ref) %>%
    group_modify(function(d,g,...) {
      
      if(g$lead >= 0) fn = function(x) lead(x,n=g$lead)
      else fn = function(x) lag(x,n=-g$lead)
      
      if(g$lead.ref >= 0) fn.ref = function(x) lead(x,n=g$lead.ref)
      else fn.ref = function(x) lag(x,n=-g$lead.ref)
      
      d %>% group_by(code) %>% arrange(date) %>% mutate(
        date.imm = fn(date),
        date.ref.imm = fn.ref(date),
        Growth.windowed.value.imm = fn(Growth.windowed.value),
        Growth.windowed.value.imm.ref = fn.ref(Growth.windowed.value.ref),
        R.imm = fn(`Mean(R)`),
        R.imm.ref = fn.ref(`Mean(R).ref`),
        R.delta = 
          fn.ref(`Mean(R).ref`)-fn(`Mean(R)`),
        R.frac = 
          fn(`Mean(R)`)-fn.ref(`Mean(R).ref`),
        Growth.windowed.delta = 
          fn(Growth.windowed.value)-fn.ref(Growth.windowed.value.ref)
      )
    }) 
  
  
  
  return(cases4)
  
}


cases4 = goCompare(cases,imms)

```

```{r}

p = ggplot(cases4 %>% filter(!is.na(immunizedDoses)),(aes(x=date,y=immunizedPercent.delta,group=paste0(code,immunizedDoses))))+geom_line(alpha=0.1)+
  facet_wrap(vars(immunizedDoses))+geom_line(data=cases4 %>% filter(!is.na(immunizedDoses) & name=="Hartlepool"), aes(colour=immunizedDoses))

p %>% standardPrintOutput::saveSlideFigure("~/Dropbox/covid19/vaccination/70sV80sProgressByLTLA")

```

```{r}

cases5 = goCompare(cases,imms, refDelay = -7:7, immDelay = 14 )

p = ggplot(cases5 %>% filter(immunizedDoses!="Second"),(aes(x=date,y=R.delta,group=paste0(code,immunizedDoses))))+geom_line(alpha=0.1)+
  facet_wrap(vars(refDelay),ncol=5)+geom_line(data =cases5 %>% filter(immunizedDoses!="Second" & name=="Hartlepool"),colour="red")+
  coord_cartesian(ylim=c(-0.75,0.75))

p %>% standardPrintOutput::saveSlideFigure("~/Dropbox/covid19/vaccination/70sV80sRDeltaByDelay")

```

```{r}

# plotDate = as.Date("2021-02-01")
# duration = 10
# tmp2Plot = cases5 %>% filter(date<plotDate & date>(plotDate-duration) & immunizedDoses != "Second") %>% mutate(fade = 1-as.numeric(plotDate-date)/duration)
# ggplot(tmp2Plot, aes(x=Growth.windowed.value.ref,y=Growth.windowed.value,group=paste0(code,ageCat),colour=ageCat, alpha=fade))+geom_path()+facet_wrap(vars(refDelay))+scale_alpha_continuous(range=c(0,0.6),guide="none")

# corr = cases5 %>% filter(immunizedDoses!="Second" & !is.na(Growth.windowed.value.imm.ref) & !is.na(Growth.windowed.value.imm)) %>% group_by(refDelay) %>% summarise(cor = sprintf("%1.2f",cor(x=Growth.windowed.value.imm.ref,y=Growth.windowed.value.imm)))
# 
# p = ggplot(cases5 %>% filter(immunizedDoses!="Second"), aes(x=Growth.windowed.value.imm.ref,y=Growth.windowed.value.imm,group=paste0(code)))+geom_path(colour="grey20",alpha=0.1)+
#   facet_wrap(vars(refDelay),ncol=5)+geom_path(data =cases5 %>% filter(immunizedDoses!="Second" & name=="Hartlepool"),colour="red")+
#   geom_label(data=corr,aes(label=cor),x=-Inf,y=Inf,vjust="inward",hjust="inward",inherit.aes = FALSE,size=3,label.size = 0)
# 
# p %>% standardPrintOutput::saveSlideFigure("~/Dropbox/covid19/vaccination/70sGrowthV80sGrowthByDelay")

corr = cases5 %>% filter(immunizedDoses!="Second" & !is.na(R.imm.ref) & !is.na(R.imm)) %>% group_by(refDelay) %>% summarise(cor = sprintf("%1.2f",cor(x=R.imm.ref,y=R.imm)))

p = ggplot(cases5 %>% filter(immunizedDoses!="Second"), aes(x=R.imm.ref,y=R.imm, group=paste0(code)))+geom_path(colour="grey20",alpha=0.1)+
  facet_wrap(vars(refDelay),ncol=5)+geom_path(data =cases5 %>% filter(immunizedDoses!="Second" & name=="Hartlepool"),colour="red")+
  geom_label(data=corr,aes(label=cor),x=-Inf,y=Inf,vjust="inward",hjust="inward",inherit.aes = FALSE,size=3,label.size = 0)

p %>% standardPrintOutput::saveSlideFigure("~/Dropbox/covid19/vaccination/70sRV80sRByDelay")

```




```{r}

# cases6 = goCompare(cases,imms, refDelay = -3, immDelay = c(0,7,14,21,28))
# 
# ggplot(cases6 %>% filter(!is.na(immunizedDoses)),aes(x=immunizedPercent.delta,y=Growth.windowed.delta))+geom_point(size=0.5,alpha=0.2)+geom_smooth(method = "lm",colour="blue",fullrange=TRUE)+geom_path(data= cases6 %>% filter(!is.na(immunizedDoses) & name=="Hartlepool"),colour="red")+
#   facet_grid(rows=vars(immunizedDoses), cols=vars(immDelay))+coord_cartesian(xlim=c(0,1))


cases6 = goCompare(cases,imms, refDelay = -3, immDelay = c(0,7,14,21,28))

p = ggplot(cases6 %>% filter(!is.na(immunizedDoses)),aes(x=immunizedPercent.delta,y=R.delta))+geom_point(size=0.5,alpha=0.2)+geom_smooth(method = "lm",colour="blue",fullrange=TRUE)+geom_path(data= cases6 %>% filter(!is.na(immunizedDoses) & name=="Hartlepool"),colour="red")+
  facet_grid(rows=vars(immunizedDoses), cols=vars(immDelay))+coord_cartesian(xlim=c(0,1),ylim=c(-0.5,0.5))

p %>% standardPrintOutput::saveSlideFigure("~/Dropbox/covid19/vaccination/70sRV80sRByImmunisationDelay")
```

```{r}
cases7 = NULL

for(ageCatRef in levels(cases$ageCat)) {
  for(ageCatComp in levels(cases$ageCat)) {
    if (ageCatComp>ageCatRef)
      cases7 = cases7 %>% bind_rows(goCompare(cases,imms, refDelay = -3, immDelay = 0,ageCatRef = ageCatRef,ageCatComp = ageCatComp))
  }
}
```

```{r}
# slopes = cases7 %>% group_by(ageCat,ageCat.ref,immunizedDoses) %>% summarise(slope = lm(Growth.windowed.delta~immunizedPercent.delta)$coefficients[["immunizedPercent.delta"]]) %>% mutate(slope=  sprintf("%1.2f",slope))
# 
# ggplot(cases7 %>% filter(immunizedDoses=="First"),aes(x=immunizedPercent.delta,y=Growth.windowed.delta))+geom_point(size=0.5,alpha=0.2)+geom_smooth(method = "lm",colour="blue",fullrange=TRUE)+
#   geom_label(data=slopes %>% filter(immunizedDoses=="First"), aes(label=slope),x=-Inf,y=Inf,vjust="inward",hjust="inward",inherit.aes = FALSE,size=3,label.size = 0)+
#   facet_grid(rows=vars(ageCat), cols=vars(ageCat.ref))+coord_cartesian(xlim=c(0,1),ylim=c(-0.05,0.05))

slopes = cases7 %>% group_by(ageCat,ageCat.ref,immunizedDoses) %>% summarise(slope = lm(R.delta~immunizedPercent.delta)$coefficients[["immunizedPercent.delta"]]) %>% mutate(slope=  sprintf("%1.2f",slope))

p = ggplot(cases7 %>% filter(immunizedDoses=="First"),aes(x=immunizedPercent.delta,y=R.delta))+geom_point(size=0.5,alpha=0.2)+geom_smooth(method = "lm",colour="blue",fullrange=TRUE)+
  geom_label(data=slopes %>% filter(immunizedDoses=="First"), aes(label=slope),x=-Inf,y=Inf,vjust="inward",hjust="inward",inherit.aes = FALSE,size=3,label.size = 0)+
  facet_grid(rows=vars(ageCat), cols=vars(ageCat.ref))+coord_cartesian(xlim=c(0,1),ylim=c(-0.5,0.5))

p %>% standardPrintOutput::saveSlideFigure("~/Dropbox/covid19/vaccination/AgeCatDeltaRComparisonByDeltaPercentImmsFirst")

```

```{r}
p = ggplot(cases7 %>% filter(immunizedDoses=="Second" & ageCat=="80+"),aes(x=immunizedPercent.delta,y=R.delta))+geom_point(size=0.5,alpha=0.2)+geom_smooth(method = "lm",colour="blue",fullrange=FALSE)+
  geom_label(data=slopes %>% filter(immunizedDoses=="Second" & ageCat=="80+"), aes(label=slope),x=-Inf,y=Inf,vjust="inward",hjust="inward",inherit.aes = FALSE,size=3,label.size = 0)+
  facet_grid(rows=vars(ageCat), cols=vars(ageCat.ref))+coord_cartesian(xlim=c(0,1),ylim=c(-0.5,0.5))

p %>% standardPrintOutput::saveSlideFigure("~/Dropbox/covid19/vaccination/AgeCatDeltaRComparisonByDeltaPercentImmsSecond")
```

<!-- ```{r} -->
<!-- dll = dpc$spim$getDeathsLineList() -->
<!-- deaths = dpc$spim$getDeathsLineListIncidence(ageBreaks = c(50,60,70,80),subgroup=NULL,codeTypes = "LAD") -->
<!-- ``` -->
